flowchart TD
    classDef apiStyle fill:#f96,stroke:#333,stroke-width:2px,color:#fff
    classDef eventStyle fill:#69f,stroke:#333,stroke-width:2px,color:#fff
    classDef cronStyle fill:#9c6,stroke:#333,stroke-width:2px,color:#fff
    classDef noopStyle fill:#3f3a50,stroke:#333,stroke-width:2px,color:#fff
    steps_finance_data_step["⚡ FinanceDataAgent"]:::eventStyle
    steps_openai_analysis_step["⚡ OpenAIAnalysisHandler"]:::eventStyle
    steps_query_api_step["🌐 FinanceQueryAPI"]:::apiStyle
    steps_response_coordinator_step["⚡ ResponseCoordinator"]:::eventStyle
    steps_result_api_step["🌐 FinanceResultAPI"]:::apiStyle
    steps_save_result_step["⚡ SaveResultHandler"]:::eventStyle
    steps_web_search_step["⚡ WebSearchAgent"]:::eventStyle
    steps_finance_data_step -->|Finance data completed| steps_response_coordinator_step
    steps_openai_analysis_step -->|Analysis completed| steps_save_result_step
    steps_query_api_step -->|Query received| steps_finance_data_step
    steps_query_api_step -->|Query received| steps_web_search_step
    steps_response_coordinator_step -->|Response completed| steps_openai_analysis_step
    steps_result_api_step -->|Analysis completed| steps_save_result_step
    steps_web_search_step -->|Web search completed| steps_response_coordinator_step 